version: '3'
services:
    test-php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        environment:
            - name=value
        volumes:
            - ./:/var/www/html
    test-nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www/html
        ports:
            - "8084:80"
        links:
            - test-php-fpm
